apiVersion: v1
kind: Secret
metadata:
  name: sonar-secrets
type: Opaque
data:
  POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: "MTIzTXVkYXI=" #123Mudar
  POSTGRESQL_CLIENT_POSTGRES_PASSWORD: "MTIzTXVkYXI=" #123Mudar
  SONARQUBE_DATABASE_PASSWORD: "MTIzTXVkYXI=" #123Mudar
  SONARQUBE_PASSWORD: "MTIzTXVkYXI=" #123Mudar

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  POSTGRESQL_PASSWORD: "MTIzTXVkYXI=" #123Mudar

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: "MTIzTXVkYXI=" #123Mudar

