apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver-deployment
spec:
  selector:
    matchLabels:
      app: nginx-webserver
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      containers:
      - name: nginx-webserver
        image: nginx:1.9.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver-serivce
spec:
  selector:
    app: nginx-webserver
  type: NodePort
  ports:
  - port: 80
    nodePort: 30952    
    
