apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: many-ingress-sample
  labels:
    name: many-ingress-sample
spec:
  rules:
  - host: rabbitmq.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rabbitmq-service
            port: 
              number: 15672
  - host: mongoexpress.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mongo-express-service
            port: 
              number: 8081
