apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.0-alpha.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: "ME_CONFIG_MONGODB_ADMINUSERNAME"
          value: "root"
        - name: "ME_CONFIG_MONGODB_ADMINPASSWORD"
          value: "123mudar"
        - name: "ME_CONFIG_MONGODB_URL"
          value: "mongodb://root:123mudar@mongodb-service:27017/"       


---


apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30953 
